project:
  type: book

book:
  title: "Remote Sensing"
  author: "Bella Chyntia Kabalmay"
  chapters:
    - index.qmd
    - week1.qmd
    - week2.qmd
    - week3.qmd
    - week4-5.qmd
    - week6.qmd
    - week7.qmd
    - week8-9.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles-book.css
    documentclass: scrreprt
    number-sections: false

editor: visual

